import pygame as pg


pg.init()

ANCHO=800
ALTO=600
ANCHO_MIN=0
ALTO_MIN=0
COLOR_BLANCO=(255,255,255)
COLOR_NEGRO=(0,0,0)
IMG_GOKU = "PYGAME_APP/images/GOKU/GOKU_NUBE22.png"
IMG_FONDO_MENU = "PYGAME_APP/images/FONDODRAGONBALL2.jpg"
IMG_APORELLOS = "PYGAME_APP/images/A_POR_ELLOS.jpg"
IMG_BOLAS_DRAGON = "PYGAME_APP/images/BOLAS_DE_DRAGON.jpg"
IMG_TERRENO_JUEGO2 = "PYGAME_APP/images/TERRENO_JUEGO.jpg"
IMG_TERRENO_JUEGO1 = "PYGAME_APP/images/TERRENO_JUEGO1.jpg"
IMG_FINAL_JUEGO = "PYGAME_APP/images/TERRENO_JUEGO.jpg"
IMG_BOLA1 = "PYGAME_APP/images/BOLAS/BOLA_ENERGIA00.png"
IMG_BOLA2 = "PYGAME_APP/images/BOLAS/BOLA_ROJA00.png"
IMG_CORAZON = "PYGAME_APP/images/CORAZON.png"
IMG_EXPLOSION ="PYGAME_APP/images/EXPLOSION/EXPLOSION.png"
CORAZON_ANCHO = 20
CORAZON_ALTO = 20
SONIDO_MENU = "PYGAME_APP/songs/MUSICA_MENU.mp3"
SONIDO_EXPLOSION = "PYGAME_APP/songs/SONIDO_COLISION.mp3"
SONIDO_PROLOGO = "PYGAME_APP/songs/MUSICA_PROLOGO.mp3"
SONIDO_FINAL = "PYGAME_APP/songs/MUSICA_FINAL.mp3"
FUENTE1 = "PYGAME_APP/fonts/Micro5-Regular.ttf"

